from fastapi import FastAPI, Request, Form
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import random

app = FastAPI()

# Mount static files and templates
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

# Game data
players = []
current_turn = 0
difficulty = "easy"

# Truth and Dare questions
questions = {
    "easy": {
        "truth": [
            "Have you ever lied to someone in this room?",
            "How often do you wash your sheets?",
            "What’s the most embarrassing problem you’ve gone to the doctor for?",
            "What is your biggest regret in life?",
            "What is the biggest secret you’re hiding from your parents?",
            "What movie is your guilty pleasure?",
            "What objectively terrible song do you love to listen to?",
            "What is the most expensive thing you’ve ever bought?",
            "If you had to marry one person in this room on the spot, who would you choose?",
            "Would you ever get plastic surgery?",
            "If you were stranded on a desert island with someone in this room, who would you choose?",
            "What’s the longest time you’ve gone without showering?",
            "Do you believe in ghosts?",
            "Have you ever been cheated on?",
            "What’s your biggest fear?",
            "What’s the strangest thing you’ve ever eaten?",
            "Who was your first celebrity crush?",
            "What’s your biggest insecurity?",
            "What’s your worst habit?",
            "Have you ever lied to get out of a bad date?",
            "Have you ever had an imaginary friend?",
            "What’s the worst thing you’ve ever said to anyone?",
            "What’s the biggest misconception about you?",
            "What’s the best piece of advice you’ve been given?",
            "If you could do any job in the world, what would it be?",
            "What’s your hidden talent?",
            "Do you still have feelings for any of your exes?",
            "Do you believe in aliens?",
            "What’s your worst fashion moment?",
            "Would you date your high school crush today?",
            "What’s your most bizarre nickname?",
            "What’s your biggest red flag?",
            "Why did your last relationship come to an end?",
            "Have you ever had a holiday fling?",
            "What is the biggest lie you’ve ever told?",
            "What do you want written on your tombstone?",
            "What’s one thing you only do when you’re alone?",
            "What is your favorite book of all time?",
            "What’s the worst date you’ve ever been on?",
            "What’s your biggest wish in life?",
            "What’s something that overwhelms you?",
            "What’s something you would do if you knew there were no consequences?",
            "Have you ever broken the law?",
            "What’s the strangest dream you’ve had?",
            "Have you ever re-worn dirty socks?",
            "What’s the strangest rumor you’ve heard about yourself?",
            "What’s the weirdest lie you’ve ever told?",
            "If you could choose a new name, what would you pick?",
            "Have you ever dined and dashed?",
            "What’s the last thing you Googled?",
            "What’s your favorite possession?",
            "Have you ever ghosted a friend?",
            "What’s your strangest dealbreaker?",
            "Where’s one place you’re dying to visit?",
            "What’s one thing in your life you wish you could change?",
            "Would you date someone shorter than you?",
            "Who are you most jealous of?",
            "Have you ever lied to your boss?",
            "What was the greatest day of your life?",
            "What app do you spend the most time on?",
            "What’s the best date you’ve been on?",
            "If you could only hear one song for the rest of your life, what would it be?",
            "Who in this group would you want to swap lives with for a week?",
            "How long was your longest relationship?",
            "What word do you hate the most?",
            "When was the last time you lied?",
            "What’s your biggest fantasy?",
            "What’s the biggest mistake you’ve ever made?",
            "What’s the one big ticket item you can’t live without?",
            "Who annoys you most in your life?",
            "Have you ever had a fling?",
            "What secretly scares you?",
            "Can you roll your tongue?",
            "What country do you want to run away to?",
            "Who would you want to help you bury a body?",
            "What do you secretly worry people judge you for?",
            "What do you do when you need alone time?",
            "What would you change about society?",
            "What book did you think was overrated?",
            "What movie did you think was overrated?",
            "Which rom-com character do you want to swap lives with?",
            "Which reptile would you least want to be locked in a room with?",
            "What’s something no one knows about you?",
            "What’s something you pretend to like but actually hate?",
            "Which reality show do you secretly want to go on?",
            "What would you buy if you won the lottery?",
            "Do you think you’d survive as a character in a horror movie?",
            "If you had to give up speaking to one person in your life, who would it be?",
            "What’s your favorite part of your life?",
            "If you had to kiss one person in this room, who would it be?",
            "What’s the wildest meal you’ve ever eaten?",
            "If you could choose anyone in the world to be president, who would it be?",
            "What’s the weirdest thing you’ve been called?",
            "What television show is your go-to comfort watch?",
            "What confuses you most about other people?",
            "Have you ever re-gifted a present?",
            "What’s a lie you’ve told your best friend?",
            "What age did you act the most chaotic?",
            "What superstitions do you believe in?",
            "What do you really think when people call their pets their kids?",
            "What’s a crime you would commit if you knew you’d never get caught?",
            "Which of your exes would you consider getting back together with?",
            "What’s something you’ve always wanted to do but never have?",
            "Do you have a guiding quote or principle you live by?",
            "What was your first kiss like?",
            "What do you think is the most romantic gesture?",
            "Have you ever lied about your age?",
            "Have you ever called out sick of work to go on a trip?",
            "Would you ever visit a nudist beach?",
            "What’s the most petty reason why you’ve ended a relationship?",
            "What’s your least favorite part of your day-to-day?"
        ],
        "dare": [
            "Ask a stranger to rate you out of ten.",
            "Eat a teaspoon of hot sauce.",
            "Show us everything inside your purse or bag.",
            "Go outside and sing the national anthem at top volume.",
            "Text your ex ‘happy birthday.’",
            "Speak in a British accent for the rest of the day.",
            "Text your crush.",
            "Let the group pick your next karaoke song.",
            "Switch clothes with another player for the rest of the game.",
            "Read the last text message you sent out loud.",
            "Share someone’s secret without divulging their name.",
            "Narrate the game for the next round.",
            "Flash someone out the window.",
            "Let another player post any photo they want to your Instagram story.",
            "Eat a surprise treat with your eyes closed.",
            "Do a sock puppet show.",
            "Post a photo of a hand with an engagement ring on Instagram.",
            "Do and post a TikTok dance of the group’s choosing.",
            "Talk in an accent for one round.",
            "Shower with your clothes on.",
            "Do 30 burpees.",
            "Have a deep conversation with an item of furniture.",
            "Give a kissing demonstration with a pillow.",
            "Eat part of a banana peel.",
            "Wear your shoes on your hands.",
            "Give each player life advice you think they need.",
            "Act like a baby.",
            "Text someone lyrics to a song line by line.",
            "Paint your nails using your teeth.",
            "Take off your socks with your teeth.",
            "Move in slow motion.",
            "Spin in a circle ten times then walk to the other room.",
            "Flirt badly with another player for one round.",
            "Do a dramatic catwalk.",
            "Do your best impersonation of a pirate.",
            "Read aloud the most intimate text you’ve sent recently.",
            "Avoid saying “like” for the rest of the game.",
            "Pretend to be a dog.",
            "Bite directly into a lemon.",
            "Read the last page of a book you haven’t finished yet.",
            "Admit who was the one who got away.",
            "Give one other player a back massage.",
            "Lick a bar of soap.",
            "Eat a snack without using your hands.",
            "Sing all your responses.",
            "Share your most scandalous hot take.",
            "Describe the plot of your favorite movie as ridiculously as you can.",
            "Bite directly into a scoop of ice cream.",
            "Do the Macarena without music.",
            "Write a poem dedicated to the other players.",
            "Give yourself a finger mustache.",
            "Let someone in the room dress you for your next big event.",
            "Keep your hands still behind your back.",
            "Put on multiple pairs of pants at one time.",
            "Eat a leaf.",
            "Do a magic trick.",
            "Tell a lie at some point during the game.",
            "Dress as a character of the group’s choosing.",
            "Act out a commercial for a product chosen by the other players.",
            "Eat five spoonfuls of a condiment of your choice.",
            "Show the most embarrassing photo on your phone.",
            "Do 50 push-ups.",
            "Do your best sexy crawl.",
            "Eat a raw piece of garlic.",
            "Let the group look through your Instagram DMs.",
            "Try and make yourself cry in front of the group.",
            "Go outside and do your best wolf howl at the moon.",
            "Plank for five whole minutes.",
            "Eat a whole block of cheese.",
            "Show us your screen time report.",
            "Eat a raw onion like an apple.",
            "Read out the last 10 things on your search history.",
            "Do an impression of another player until your next turn.",
            "Walk next door with a measuring cup and ask for a cup of sugar.",
            "Yell out the first word that comes to your mind.",
            "Insult everyone in the room.",
            "Let another player style your hair and leave it that way for the rest of the game.",
            "Do a freestyle rap about the other players for one minute.",
            "Show the weirdest item you have in your bag.",
            "Tell the most embarrassing that's ever happened to you.",
            "Smell another player’s armpit.",
            "Play air guitar for two minutes straight.",
            "Tell each player who you think their celebrity look alike is.",
            "Let the group decide your outfit for the night.",
            "Try to drink a glass of water without using your hands.",
            "Eat a raw egg.",
            "Try to lick your elbow.",
            "Burp the alphabet.",
            "Let another player draw a tattoo on you in permanent marker.",
            "Attempt to juggle two or three items of the asker’s choosing.",
            "Serenade the person to your right.",
            "Keep your eyes closed until it’s your turn again.",
            "Sit in the corner of the room without speaking to anyone for the next 10 minutes.",
            "Try to put your whole fist in your mouth.",
            "Put your clothing on backwards for the rest of the evening.",
            "Try not to laugh for the next 10 minutes.",
            "Fill your mouth with drink and gargle your answer to the next Truth.",
            "Act like a chicken until your next turn.",
            "Let the player to your right do or redo your makeup.",
            "Give a foot massage to the person on your left.",
            "Show the group your driver’s license photo.",
            "Shower with your clothes on.",
            "Do five minutes of stand-up comedy.",
            "Reply to the first five Instagram Stories on your timeline."]
    },
    "medium": {
        "truth": ["When do you feel the sexiest?",
                   "When do you feel the sexiest?",
                   "When do I look the most attractive?",
                   "What song puts you in the mood?",
                   "What's something non-sexual that turns you on?"
                   "What turns you on?",
                   "What's your biggest turn-off?",
                   "What’s your favorite thing I do in bed?",
                   "What's your favorite body part of mine?",
                   "What's your biggest guilty pleasure?",
                    "What outfit do I look the sexiest in?",
                    "Do you ever clear your search history?",
                    "Have you ever been in a secret relationship?",
                    "Have you ever been turned on at work?",
                    "What’s your favorite place to be kissed?",
                    "What’s your favorite place to be kissed?",
                    "Have you ever been caught in action?",
                    "Have you ever been caught in action,If so, by who?",
                    "Have you ever gone skinny dipping?",
                    "Do you prefer giving or receiving?",
                    "What’s your biggest sexual fantasy?",
                    "What are your thoughts on open relationships?",
                    "What’s your most awkward or embarrassing sexual experience?",
                    "Where’s the craziest place you’ve had sex?",
                    "How would you define cheating?",
                    "Where’s your favorite place to be kissed?",
                    "What was your sexual awakening?",
                    "What’s the biggest lie you’ve ever told an ex?",
                    "Who’s your celebrity hall pass?",
                    "Have you ever sent a dirty text to the wrong person?",
                    "If you woke up like me tomorrow, what’s the first thing you would do?",
                    "Would you rather give up kissing or sex?",
                    "Would you rather have average sex every day or incredible sex once a month?",
                    "Do you prefer being dominant or submissive?",
                    "What’s your favorite position?",
                    "Do you prefer morning sex or night sex?",
                    "What’s your love language?",
                    "What’s your love language?",
                    "What’s the first thing you noticed about me?",
                    "What’s your favorite thing we do together?",
                    "What’s your favorite memory of us?",
                    "What’s the most annoying thing I do?",
                    "What’s your favorite thing about me?",
                    "When was your first kiss?",
                    "What’s your biggest red flag in a relationship?",
                    "What’s the most romantic gift you’ve ever received?",
                    "Do you believe in soulmates?",
                    "Do you believe in love at first sight?",
                    "How would you approach me if we weren’t dating?",
                    "Do you think age gaps matter in a relationship?",
                    "When did you realize you really liked me?",
                    "What’s the most embarrassing thing you’ve ever done to get someone’s attention?",
                    "What’s a secret you’ve never told anyone?",
                    "What’s your biggest fear about our relationship?",
                    "How did you know I was attracted to you?",
                    "What’s your favorite meal that I cook?",
                    "What was your longest relationship?",
                    "What’s the most childish thing you’ve ever done in a relationship?",
                    "When was the first time you fell in love?",
                    "When was the first time you fell in love?"],


        "dare": ["Send me a sexy photo of yourself that I’ve never seen.",
                 "Send me a sexy photo of yourself that I’ve never seen.",
"Send me a video of yourself performing a sexy dance.",
"Send me a sexy audio message.",
"Send me a flirty text only using emojis.",
"Let me go through your search history.",
"Play me a song that puts you in the mood.",
"Pretend you don’t know me, and try to pick me up.",
"Order a sexy outfit for me online.",
"Try to find my most ticklish spot.",
"Pretend to be my pet for the next 10 minutes.",
"Do as many pushups as you can with me sitting on you.",
"Recreate a couple’s yoga pose with me.",
"Spell the alphabet on your favorite part of my body.",
"Describe your biggest turn-on without naming it.",
"“Accidentally” text your sibling a sexy message.",
"Make me a dating profile on Tinder.",
"Try to turn me on without touching me.",
"Try to turn me on without touching me.",
"Give me your best sexy crawl.",
"Make out with an object in your room."
"Pick one piece of clothing you want me to take off.",
"Perform a strip tease for me.",
"Call your friend and moan in the middle of the conversation.",
"Call your friend and describe your biggest turn-on.",
"Leave your friend a spicy voicemail.",
"Describe the hottest dream you’ve had about me.",
"Strip down to your underwear for the rest of the game.",
"Spell a word on my body, using your tongue.",
"Let me shave one part of your body.",
"Switch outfits with me (including underwear).",
"Create an outfit with anything but clothes.",
"Lick whipped cream off my body.",
"Hold an ice cube between your teeth and run it across my neck.",
"Write my name on your chest and send me a photo.",
"Kiss your favorite part of my body.",
"Take off one piece of my clothing with your teeth.",
"Eat food of your choice in the most seductive way possible.",
"Give me a lap dance.",
"Tell me something you’ve never told anyone before.",
"Tell me something you’ve never told anyone before.",
"Send me the most embarrassing photo of yourself.",
"Record an ASMR video for me.",
"Write me a romantic poem.",
"Draw a portrait of me.",
"Tell me about your first crush.",
"Do your best impression of me.",
"Sing a romantic song for me.",
"Braid my hair.",
"Give me a foot massage."
"Let me give you a makeover.",
"Act out your favorite romantic scene with me."]
    },
    "hard": {
        "truth": ["What's a seemingly nonsexual thing that turns you on?"
 "Have you ever had sex with more than one person in a day?"
 "What's the biggest age difference you've ever had with a partner?",
 "What's the most embarrassing thing that’s happened to you during sex?",
"Have you ever cheated?  Did it turn you on?",
"Have you ever turned down a sexual opportunity and regretted it?",
" When did you learn what sex was? What’s the story?",
"Have you ever faked an orgasm?",
 "Have you ever accidentally sent a sext to the wrong person?",
" How do you feel about shower sex? Love it, hate it, or super neutral?",
" What's the sexiest song you've ever heard? What about it turns you on?",
" What's the most amount of times you've orgasmed in a day?",
"If we opened up our relationship, who would be the first person you’d want to have sex with?",
 "Who would be in your dream orgy?",
"What do you remember most about the first time you ever had sex?",
"Who is the weirdest person you’ve had a sex dream about?",
"If you could have sex with one person from your past again, who would it be?",
"Would you ever want to watch me have sex with someone else?",
" What’s one sex toy you want me to try on you?",
 "What’s a fantasy you’ve never told me about?",
"What memory from our sex life turns you on the most?",
"What would be your dream role-play scenario?",
"If you could hook up with one of my friends, who would it be?",
"What do you think I’m best at in bed?",
 "Have you ever gotten turned on at work (or while WFH)? What did you do about it?",
"Have you ever hooked up with a stranger or had a one-night stand?",
"Do you prefer using your tongue or fingers on me? Which do you like me to use on you?",
"How do you feel about swinging or partner swapping? Does the idea turn you on?",
"What's something I do that isn't sexual but turns you on?",
"Would you ever want to go to a sex club with me?",
" Where is the strangest place you’ve ever masturbated?",
"What’s #1 on your sexual bucket list right now?",
"Have you ever been caught having sex?",
"Have you ever accidentally walked in on anyone getting it on?",
"Do you ever watch porn? Tell me what type you usually gravitate toward.",
" What’s the kinkiest thought you’ve ever had about me?",
"What’s a sex act most people like that you think is overrated?",
"What sexual activity (or activities) do you think is underrated?",
"Have you ever fantasized about a teacher or authority figure? Who was it and why?",
"Do you know the last name of everyone you’ve had sex with? What about first?",
"What is your favorite body part for me to suck on?",
"Would you prefer to dominate me in bed or do you want me to dominate you in bed?",
"Do you like being nibbled on or lightly bitten? Where?",
"What's your favorite sex toy to use on me?",
 "What's the kinkiest thing you've ever done?",
"What’s the hottest sex dream you’ve ever had?",
"Tell me one thing I could do that would make you immediately orgasm.",
"Which is your favorite kind of sex: soft, slow, and sweet or aggressive, fast, and feisty?",
"If I gave you a free pass to hook up with one celebrity, who would it be and why?",
"What item of clothing do you think I look sexiest in?",
"Describe my in-bed personality in three words.",
"If I were handcuffed to the bed, what would you do to me?",
"If you were to create an original sex move, what would you call it?",
"What's something dirty you've always been too shy to say to me in bed?",
"If we could only have sex in one position for a month, what position would you pick?",
" Is there something you've seen in a steamy movie that you'd like to try?",
"What sex move of mine is your favorite? Give me all the dirty details about why you like it.",
"What kind of foreplay would you like to try the next time we are in bed?",
"Where do you think our most romantic kiss took place? Tell me everything you remember about it.",
"When I am on top of you, what's your favorite part of me to watch?",
"How often do you masturbate? How often is it about me?",
 "If you could go back and change anything about the first time we had sex, what would it be and why?",
"What’s your favorite text I’ve sent you when we’ve been sexting?",
"What is your least favorite sex position and why?",
"How do you feel about threesomes? Have you ever had one, and if not, would you ever have one?",
"What do you think the sexiest part of my body is?",
"What do you think the sexiest part of your body is?",
"Have you ever fantasized about anything sexual with someone of your same sex?",
"What’s the wildest place you’ve ever had sex?",
"What were you thinking when you first saw me naked?",
 "Fuck, Marry, Kill: Missionary, doggy, and oral sex.",
 "Have you ever fallen asleep during sex?"],


        "dare": ["Pretend we’re strangers at a bar and you just spotted me. Try to pick me up.",
"Go down on me in a position we’ve never tried before.",
"Draw me (like one of your French girls).",
"Roleplay that you’re a professor and I’m your student. Seduce me.",
"Describe what type of lingerie really turns you on while making eye contact with me. If you laugh, you have to buy some for me.",
"Take out your wallet and pretend to be a patron at a strip club while I dance for you. (Tips are more than encouraged.)",
"Go to the kitchen and make me the sexiest snack you can think of, Master Chef style. The catch? You only have three minutes, and you’re the plate.",
"I’ll pick a song and you have to give me a lap dance. Blindfolded.",
"You can’t say my name for the rest of the game, but instead, have to call me any nickname I choose. Every time you mess up, I get to spank you.",
"Act out your sexiest fantasy without using your words. Props, however, are highly encouraged.",
"Go skinny dipping with me. (If you don’t have a private pool, get creative! The bathtub, shower, or a water fight in the kitchen all count.)",
"Trade clothes with me for the rest of the game. Once you put mine on, blast your fave hype song and show off your new look like a runway model.",
"Try to literally (li li li) lick yourself from your head to your toes. You only get three “help” spots where I can jump in, so use wisely.",
"Show me the last porn video you watched.",
"Watch me touch myself for five minutes. You’re not allowed to touch me or yourself while I do.",
"Kiss a part of my body you want to cum on.",
"Take my hand and put it on a part of your body you’d like me to pay more attention to. Guide my hand and show me how you want to be touched.",
"You have one minute to turn me on using only your feet",
"Show me a video (an ~adult~ one, duh) of something you’d like us to try together.",
"Put on a song you find really sexy and go down on me for the length of it.",
"Imitate what I sound like when I orgasm.",
"Blindfold me and write something sexy on my body in lipstick.",
"Go in the other room and sext me the dirtiest thing you can think of.",
"Show me how you touch yourself when I’m not around.",
"Take off your pants and give me your best twerk. Now try it upside down on the wall.",
"Host a sexy, five-minute yoga class for me with lots of sensual stretching and downward dogging.",
" Call me from the other room. When it goes to voicemail, leave me an explicit message outlining exactly what you want to do to me.",
"Demonstrate your best oral sex move on the nearest appropriate object.",
"Put on 'Pony' by Ginuwine, and vacuum seductively for the length of the song.",
"Turn out the lights and try to turn me on *only* using sounds. You have two minutes and if you fail, you owe me a sexual favor.",
"Give me a sensual foot massage. The hotter, the better.",
"Kiss your three favorite body parts of my body.",
"Put on a timer and act out as many sexual positions as you can with your clothes on.",
"Pick out three sex toys online you’d want to try with me. I get to pick my favorite one and you have to order it right now.",
"Take a selfie of your most outrageous “O” face. Now put that as your lock screen, and keep it that way for the next 48 hours. If you change it before time’s up, you owe me dinner.",
"Give me a detailed, charismatic cooking demonstration of “How to Make Cereal.” The catch: You gotta do it nude.",
"Set the mood and reenact the most romantic movie kiss you can think of with me. If you need some inspo, try Titanic, The Notebook, or even Spider-Man. Who knows, things might get so heated you find yourself reenacting some Bridgerton scenes next *wink wink.",
"Go find your old Halloween costume and put it on for me. Then, let's decide what to role-play.",
"Place whipped cream on your favorite parts of my body. Now, lick it off.",
"Eat a strawberry in the most sensual way possible.",
"Engage in foreplay with me for five minutes with one rule: You're allowed to kiss me anywhere but my mouth.",
"Give me a massage anywhere on my body for 10 minutes.",
"Do something to me right now that you've been fantasizing about.",
"Find something sweet to swipe across your lips and give me a passionate kiss.",
"Drag me to the closet for an adult round of seven minutes in heaven. You must keep the making out above the belt.",
"Stimulate two parts of my body at once. Use your hands on one part and lips on another.",
"Using your mouth, make your way from my wrist to my ear. Take your time!",
"In your most sultry voice, tell me what you loved about the last time we had sex.",
"Hop in the shower with me and wash my body, making sure not to miss any hard spots.",
"You have ten seconds to excite me just by kissing. Hint: You're not limited to my lips.",
"Imitate my most flexible sex move.",
"Make out with me like we used to before we started having sex.",
"Pole dance with an imaginary pole for the length of an entire song of my choice.",
"Play me a song you’d like to have sex to.",
"Using your fingers, find a way to give me goosebumps right now.",
"Give me a sensual massage. Start at my feet and work your way up.",
"For the next 60 seconds, touch yourself like you’d like to touch me.",
"Spell out a short, sultry message on my body…with your tongue.",
" Initiate a roleplay scenario and make me guess what your character is.",
"I’m going to go into the other room and dab perfume or cologne somewhere on my body. You have to sniff everywhere until you figure out where I put it on.",
"Pop an ice cube in your mouth and go down on me for 15 seconds.",
"Put my cell on vibrate, then place it somewhere on my body. Now, call me.",
"Pour a trail of sugar from the small of my back to my neck. Now, lick it up.",
"Take off my underwear…with your mouth.",
"Dip your fingertips in mouthwash and then rub my nipples so I’ll get an erotic, tingly sensation the moment you touch me.",
"Pick a spot on my body that isn’t usually considered sexual—elbows, knees, ankles—and lavish it with kisses until I’m turned on.",
"Fuck me like it’s the first time."]
    }
}

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.post("/start")
async def start_game(player1: str = Form(...), player2: str = Form(...), gender1: str = Form(...), gender2: str = Form(...), difficulty_level: str = Form(...)):
    global players, current_turn, difficulty
    players = [{"name": player1, "gender": gender1}, {"name": player2, "gender": gender2}]
    current_turn = random.randint(0, 1)
    difficulty = difficulty_level
    return RedirectResponse(url="/game", status_code=303)

@app.get("/game", response_class=HTMLResponse)
async def game(request: Request):
    global current_turn
    player = players[current_turn]
    return templates.TemplateResponse("game.html", {"request": request, "player": player, "difficulty": difficulty})

@app.post("/play")
async def play(choice: str = Form(...)):
    global current_turn
    question_type = choice.lower()
    question_list = questions[difficulty][question_type]
    question = random.choice(question_list)
    current_player = players[current_turn]["name"]
    current_turn = (current_turn + 1) % 2
    next_player = players[current_turn]["name"]
    return {"question": question, "current_player": current_player, "next_player": next_player}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)